### ISSUE TITLE
Big-endian support

### ISSUE THREAD

**Issue by hasufell** [hasufell/abstract-filepath#12]
It appears that `writeWord16Array#` aligns the word depending on current platform endianness:

https://github.com/hasufell/abstract-filepath/blob/2f54c68cdff99d171178e2a15421f5c92b173a7a/lib/AFP/Data/ByteString/Short/Word16.hs#L439

That means on LE systems (most linux ones), it flips the order before writing it to the bytestring. As such, it appears that `Word16` has in fact `Word16BE` semantics, so the module [Data.Word16](https://github.com/hasufell/word16/blob/48ff3aa6f76b624965470c852a14fc9e480dc639/lib/Data/Word16.hs) uses the BE encoding of words.

This probably means, that, for BE platforms, we have to perform a byte-swap before calling `writeWord16Array#`, since the expected encoding is UTF-16LE for the windows API?

**Comment by hasufell** [comment]
@mpickering

**Comment by hasufell** [comment]
I've worked around it by writing word8 arrays in the order I want instead: https://github.com/hasufell/abstract-filepath/commit/93bc4159d6513d052ee1ef70d875c0d60bfb4216

**Comment by Bodigrim** [comment]
I do not quite follow what you mean by "the module Data.Word16 uses the BE encoding of words". As much as I can tell, `Data.Word16` does not make such call and uses a platform-dependent representation of `Word16`. 

The only BE hardware in wide usage are IBM mainframes, almost everything else is LE. Windows has never supported BE hardware, I believe.

**Comment by hasufell** [comment]
> I do not quite follow what you mean by "the module Data.Word16 uses the BE encoding of words". As much as I can tell, `Data.Word16` does not make such call and uses a platform-dependent representation of `Word16`. 
> 

From my understanding `Data.Word16` is the same across all platforms, just like any integer type.

Differences are only observable, when you use word16 primops to write them. On LE platforms, you get a byte swap, on BE you don't. 

Is this not correct? 


> The only BE hardware in wide usage are IBM mainframes, almost everything else is LE. Windows has never supported BE hardware, I believe.

Well, but you should be able to serialize a windows filepath on a BE platform correctly. It must be platform agnostic.

**Comment by Bodigrim** [comment]
`Word16` register itself does not have any encoding associated, e. g., `shiftL` / `shiftR` work the same for both endianness. So saying ["All functions assumes that Word16 is encoded in BE"](https://hackage.haskell.org/package/word16-0.1.0.0/docs/Data-Word16.html) is redundant and a bit confusing.

It's only when you write `Word16` to a byte buffer, encoding happens and endianness comes into play.

**Comment by hasufell** [comment]
> `Word16` register itself does not have any encoding associated, e. g., `shiftL` / `shiftR` work the same for both endianness. So saying ["All functions assumes that Word16 is encoded in BE"](https://hackage.haskell.org/package/word16-0.1.0.0/docs/Data-Word16.html) is redundant and a bit confusing.
> 
> It's only when you write `Word16` to a byte buffer, encoding happens and endianness comes into play. 

That's exactly what I meant 🤔😅
